name: CI

on:
    push:
        branches:
            - 'staging'
            - '5-choose-cicd-mysqlphp-solution'
    pull_request:
        branches:
            - '*'

jobs:
    setup-cakephp:
        name: Basic cakephp installation
        runs-on: ubuntu-22.04
        steps:
            - name: Setup MySQL 8.0
              run: |
                  sudo service mysql start
                  mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE cakephp;'

            - uses: actions/checkout@v4

            - name: Composer install
              run: composer install


